FROM leafok/lbbs-apache

RUN mkdir -p /var/www/html/conf

COPY ./conf/db_conn.conf.php /var/www/html/conf/db_conn.conf.php
COPY ./conf/smtp.conf.php /var/www/html/conf/smtp.conf.php
COPY ./leafok_bbs/TODO/conf/badwords.conf /var/www/html/conf/badwords.conf
COPY ./leafok_bbs/TODO/conf/deny_reg.conf /var/www/html/conf/deny_reg.conf

RUN chown -R www-data:www-data /var/www/html/conf
