# Stage for Build
FROM debian:13-slim AS builder

RUN apt-get update && apt-get install -y \
    gcc make gdb autoconf automake libtool pkg-config \
    libssh-dev libpcre2-dev libmariadb-dev libsystemd-dev \
    php-cli php-mysql \
    && rm -rf /var/lib/apt/lists/*

COPY ./lbbs /home/lbbs_src
WORKDIR /home/lbbs_src

RUN autoreconf --install --force
RUN ./configure --prefix=/usr/local/lbbs \
    && make && make install

# Stage for Runtime
FROM debian:13-slim

# Install locales package and generate en_US.UTF-8
RUN apt-get update && apt-get install -y locales \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for the locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y \
    libssh-4 libpcre2-8-0 libmariadb3 libsystemd0 \
    php-cli php-mysql \
    && rm -rf /var/lib/apt/lists/*

# Copy the custom configuration file
COPY ./lbbs/Dockerfile/php.ini /usr/local/etc/php/php.ini

COPY --from=builder /usr/local/lbbs /usr/local/lbbs

COPY ./conf/bbsd.conf /usr/local/lbbs/conf/bbsd.conf
RUN cp /usr/local/lbbs/conf/badwords.conf.default /usr/local/lbbs/conf/badwords.conf
RUN cp /usr/local/lbbs/conf/bbsnet.conf.default /usr/local/lbbs/conf/bbsnet.conf
COPY ./conf/db_conn.conf.php /usr/local/lbbs/utils/conf/db_conn.conf.php

COPY ./data/eula.txt /usr/local/lbbs/data/eula.txt
COPY ./data/register.txt /usr/local/lbbs/data/register.txt
COPY ./data/welcome.txt /usr/local/lbbs/data/welcome.txt

COPY ./script/bbsd_prepare.sh /usr/local/lbbs/bin/bbsd_prepare.sh

WORKDIR /usr/local/lbbs
