FROM composer:latest AS composer_installer

# Set working directory
RUN mkdir -p /usr/local/composer

WORKDIR /usr/local/composer

COPY ./leafok_bbs/composer.json ./leafok_bbs/composer.lock ./
RUN /usr/bin/composer install --prefer-dist --no-scripts --no-progress

# Use the official Apache image
FROM httpd:2.4

# Copy the custom configuration file
COPY ./leafok_bbs/Dockerfile/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
RUN sed -i 's/#Include conf\/extra\/httpd-vhosts.conf/Include conf\/extra\/httpd-vhosts.conf/' /usr/local/apache2/conf/httpd.conf

# Copy web application files
COPY ./leafok_bbs/bbs /var/www/html/bbs
COPY ./leafok_bbs/gen_ex /var/www/html/gen_ex
COPY ./leafok_bbs/js /var/www/html/js
COPY ./leafok_bbs/lib /var/www/html/lib
COPY ./leafok_bbs/manage /var/www/html/manage
RUN mkdir -p /var/www/html/bbs/cache \
    /var/www/html/bbs/upload \
    /var/www/html/bbs/images/face/upload_photo \
    /var/www/html/conf /var/www/html/stat

# Copy the composer binary from the installer stage into your final image
COPY --from=composer_installer /usr/local/composer/vendor /var/www/html/vendor

COPY ./conf/db_conn.conf.php /var/www/html/conf/db_conn.conf.php
COPY ./conf/site.conf.php /var/www/html/conf/site.conf.php
COPY ./conf/smtp.conf.php /var/www/html/conf/smtp.conf.php
COPY ./leafok_bbs/TODO/conf/badwords.conf /var/www/html/conf/badwords.conf
COPY ./leafok_bbs/TODO/conf/deny_reg.conf /var/www/html/conf/deny_reg.conf

COPY ./data/eula.txt /var/www/html/bbs/doc/eula.txt

# Set ownership to www-data user and group
RUN chown -R www-data:www-data /var/www/html
